### ISSUE TITLE
Shoveler does not start with one corrupted file

### ISSUE THREAD

**Issue by biozit** [opensciencegrid/xrootd-monitoring-shoveler#13]
`PANIC[2023-01-11T09:37:00-08:00] Failed to create queue: unable to create segment for /tmp/shoveler-queue: unable to load queue segment in /tmp/shoveler-queue: segment file /tmp/shoveler-queue/0000000006497.dque is corrupted: error reading gob data from file: unexpected EOF `

how about ignore the corrupted file?

**Comment by biozit** [comment]
```
file /tmp/shoveler-queue/0000000004553.dque is corrupted: error reading object length (read 2/4 bytes): unexpected EOF 
panic: (*logrus.Entry) 0xc0003ce070

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0003ce000, 0x0, 0xc0005d07e0, 0x102)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x2ba
github.com/sirupsen/logrus.(*Entry).Log(0xc0003ce000, 0x0, 0xc000119bb8, 0x1, 0x1)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x86
github.com/sirupsen/logrus.(*Entry).Logln(0xc0003ce000, 0xc000000000, 0xc000119c90, 0x2, 0x2)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:383 +0xd6
github.com/sirupsen/logrus.(*Logger).Logln(0xc0000c8000, 0x0, 0xc000119c90, 0x2, 0x2)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:292 +0x7e
github.com/sirupsen/logrus.(*Logger).Panicln(...)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:333
github.com/sirupsen/logrus.Panicln(...)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/exported.go:264
main.(*ConfirmationQueue).Init(0xc0002008d0, 0xc0002008d0)
	/root/shoveler/xrootd-monitoring-shoveler/queue.go:54 +0x218
main.NewConfirmationQueue(...)
	/root/shoveler/xrootd-monitoring-shoveler/queue.go:34
main.main()
	/root/shoveler/xrootd-monitoring-shoveler/main.go:39 +0x2a5
[1350] root@redirector /tmp/shoveler-queue# ls -lha /tmp/shoveler-queue/0000000004553.dque 
-rw-r--r--. 1 root root 3.0M Feb 10 18:26 /tmp/shoveler-queue/0000000004553.dque

```

**Comment by biozit** [comment]
@djw8605 :-)

**Comment by djw8605** [comment]
Are you still seeing this problem?

**Comment by djw8605** [comment]
I don't think this is an issue anymore, right?
